name: Deploy to Aliyun Server

on:
  workflow_dispatch:
    inputs:
      deployMessage:
        description: 'Deployment message'
        required: true
        default: 'Manual deployment triggered'


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Login to Aliyun Container Registry
      uses: docker/login-action@v2
      with:
        registry: crpi-7pvk5xebkb6d01bu.cn-hangzhou.personal.cr.aliyuncs.com
        username: 爱新觉罗钮钴禄东东
        password: ${{ secrets.ALIYUN_CR_PASSWORD }}
    
    - name: Generate config file
      run: |
        envsubst < configs/config.yaml.template > configs/config.yaml
      env:
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: crpi-7pvk5xebkb6d01bu.cn-hangzhou.personal.cr.aliyuncs.com/docker_sky_private/blog-service:${{ github.sha }},crpi-7pvk5xebkb6d01bu.cn-hangzhou.personal.cr.aliyuncs.com/docker_sky_private/blog-service:latest

    - name: Deploy to Aliyun Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ALIYUN_HOST }}
        username: ${{ secrets.ALIYUN_USERNAME }}
        key: ${{ secrets.ALIYUN_SERVER_SSH_KEY }}
        script: |
          docker login --username=爱新觉罗钮钴禄东东 --password=${{ secrets.ALIYUN_CR_PASSWORD }} crpi-7pvk5xebkb6d01bu.cn-hangzhou.personal.cr.aliyuncs.com
          docker pull crpi-7pvk5xebkb6d01bu.cn-hangzhou.personal.cr.aliyuncs.com/docker_sky_private/blog-service:latest
          docker stop blog-service || true
          docker rm blog-service || true
          docker run -d \
            --name blog-service \
            -p 8080:8080 \
            --restart always \
            crpi-7pvk5xebkb6d01bu.cn-hangzhou.personal.cr.aliyuncs.com/docker_sky_private/blog-service:latest